/* ALH.h
   Generated by gSOAP 2.7.12 from I_ALBroker.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef ALH_H
#define ALH_H
#include "ALStub.h"

namespace AL {
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_byte
#define SOAP_TYPE_AL_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_AL_xsd__int
#define SOAP_TYPE_AL_xsd__int (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_AL_int
#define SOAP_TYPE_AL_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_AL_xsd__float
#define SOAP_TYPE_AL_xsd__float (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_xsd__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_AL_float
#define SOAP_TYPE_AL_float (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_AL_xsd__double
#define SOAP_TYPE_AL_xsd__double (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_xsd__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_xsd__double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_AL_double
#define SOAP_TYPE_AL_double (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_TYPE_AL_xsd__bool
#define SOAP_TYPE_AL_xsd__bool (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_xsd__bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_xsd__bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_AL_bool
#define SOAP_TYPE_AL_bool (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_AL_al__ALModuleInfo
#define SOAP_TYPE_AL_al__ALModuleInfo (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_al__ALModuleInfo(struct soap*, const char*, int, const al__ALModuleInfo *, const char*);
SOAP_FMAC3 al__ALModuleInfo * SOAP_FMAC4 soap_get_al__ALModuleInfo(struct soap*, al__ALModuleInfo *, const char*, const char*);
SOAP_FMAC3 al__ALModuleInfo * SOAP_FMAC4 soap_in_al__ALModuleInfo(struct soap*, const char*, al__ALModuleInfo *, const char*);
SOAP_FMAC5 al__ALModuleInfo * SOAP_FMAC6 soap_new_al__ALModuleInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_al__ALModuleInfo(struct soap*, al__ALModuleInfo*);
SOAP_FMAC3 al__ALModuleInfo * SOAP_FMAC4 soap_instantiate_al__ALModuleInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_al__ALModuleInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_xsd__anyType
#define SOAP_TYPE_AL_xsd__anyType (21)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__anyType(struct soap*, ALValue *);
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__anyType(struct soap*, const ALValue *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyType(struct soap*, const ALValue *, const char*, const char*);
SOAP_FMAC1 int SOAP_FMAC2 soap_out_xsd__anyType(struct soap*, const char*, int, const ALValue *, const char*);
SOAP_FMAC3 ALValue * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, ALValue *, const char*, const char*);
SOAP_FMAC1 ALValue * SOAP_FMAC2 soap_in_xsd__anyType(struct soap*, const char*, ALValue *, const char*);
SOAP_FMAC5 ALValue * SOAP_FMAC6 soap_new_xsd__anyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyType(struct soap*, ALValue*);
SOAP_FMAC3 ALValue * SOAP_FMAC4 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_xsd__string
#define SOAP_TYPE_AL_xsd__string (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, std::string const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_xsd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_xsd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_std__string
#define SOAP_TYPE_AL_std__string (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC5 std::string * SOAP_FMAC6 soap_new_std__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__string(struct soap*, std::string*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_SOAP_ENV__Fault
#define SOAP_TYPE_AL_SOAP_ENV__Fault (118)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_SOAP_ENV__Reason
#define SOAP_TYPE_AL_SOAP_ENV__Reason (117)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_SOAP_ENV__Detail
#define SOAP_TYPE_AL_SOAP_ENV__Detail (116)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_SOAP_ENV__Code
#define SOAP_TYPE_AL_SOAP_ENV__Code (114)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_SOAP_ENV__Header
#define SOAP_TYPE_AL_SOAP_ENV__Header (113)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_AL_albroker__getDebugTaskList
#define SOAP_TYPE_AL_albroker__getDebugTaskList (112)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getDebugTaskList(struct soap*, struct albroker__getDebugTaskList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getDebugTaskList(struct soap*, const struct albroker__getDebugTaskList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getDebugTaskList(struct soap*, const struct albroker__getDebugTaskList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getDebugTaskList(struct soap*, const char*, int, const struct albroker__getDebugTaskList *, const char*);
SOAP_FMAC3 struct albroker__getDebugTaskList * SOAP_FMAC4 soap_get_albroker__getDebugTaskList(struct soap*, struct albroker__getDebugTaskList *, const char*, const char*);
SOAP_FMAC3 struct albroker__getDebugTaskList * SOAP_FMAC4 soap_in_albroker__getDebugTaskList(struct soap*, const char*, struct albroker__getDebugTaskList *, const char*);
SOAP_FMAC5 struct albroker__getDebugTaskList * SOAP_FMAC6 soap_new_albroker__getDebugTaskList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getDebugTaskList(struct soap*, struct albroker__getDebugTaskList*);
SOAP_FMAC3 struct albroker__getDebugTaskList * SOAP_FMAC4 soap_instantiate_albroker__getDebugTaskList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getDebugTaskList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__stopTaskName
#define SOAP_TYPE_AL_albroker__stopTaskName (109)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__stopTaskName(struct soap*, struct albroker__stopTaskName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__stopTaskName(struct soap*, const struct albroker__stopTaskName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__stopTaskName(struct soap*, const struct albroker__stopTaskName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__stopTaskName(struct soap*, const char*, int, const struct albroker__stopTaskName *, const char*);
SOAP_FMAC3 struct albroker__stopTaskName * SOAP_FMAC4 soap_get_albroker__stopTaskName(struct soap*, struct albroker__stopTaskName *, const char*, const char*);
SOAP_FMAC3 struct albroker__stopTaskName * SOAP_FMAC4 soap_in_albroker__stopTaskName(struct soap*, const char*, struct albroker__stopTaskName *, const char*);
SOAP_FMAC5 struct albroker__stopTaskName * SOAP_FMAC6 soap_new_albroker__stopTaskName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__stopTaskName(struct soap*, struct albroker__stopTaskName*);
SOAP_FMAC3 struct albroker__stopTaskName * SOAP_FMAC4 soap_instantiate_albroker__stopTaskName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__stopTaskName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__stopTaskNameResponse
#define SOAP_TYPE_AL_albroker__stopTaskNameResponse (108)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__stopTaskNameResponse(struct soap*, struct albroker__stopTaskNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__stopTaskNameResponse(struct soap*, const struct albroker__stopTaskNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__stopTaskNameResponse(struct soap*, const struct albroker__stopTaskNameResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__stopTaskNameResponse(struct soap*, const char*, int, const struct albroker__stopTaskNameResponse *, const char*);
SOAP_FMAC3 struct albroker__stopTaskNameResponse * SOAP_FMAC4 soap_get_albroker__stopTaskNameResponse(struct soap*, struct albroker__stopTaskNameResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__stopTaskNameResponse * SOAP_FMAC4 soap_in_albroker__stopTaskNameResponse(struct soap*, const char*, struct albroker__stopTaskNameResponse *, const char*);
SOAP_FMAC5 struct albroker__stopTaskNameResponse * SOAP_FMAC6 soap_new_albroker__stopTaskNameResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__stopTaskNameResponse(struct soap*, struct albroker__stopTaskNameResponse*);
SOAP_FMAC3 struct albroker__stopTaskNameResponse * SOAP_FMAC4 soap_instantiate_albroker__stopTaskNameResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__stopTaskNameResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__stopTask
#define SOAP_TYPE_AL_albroker__stopTask (106)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__stopTask(struct soap*, struct albroker__stopTask *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__stopTask(struct soap*, const struct albroker__stopTask *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__stopTask(struct soap*, const struct albroker__stopTask *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__stopTask(struct soap*, const char*, int, const struct albroker__stopTask *, const char*);
SOAP_FMAC3 struct albroker__stopTask * SOAP_FMAC4 soap_get_albroker__stopTask(struct soap*, struct albroker__stopTask *, const char*, const char*);
SOAP_FMAC3 struct albroker__stopTask * SOAP_FMAC4 soap_in_albroker__stopTask(struct soap*, const char*, struct albroker__stopTask *, const char*);
SOAP_FMAC5 struct albroker__stopTask * SOAP_FMAC6 soap_new_albroker__stopTask(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__stopTask(struct soap*, struct albroker__stopTask*);
SOAP_FMAC3 struct albroker__stopTask * SOAP_FMAC4 soap_instantiate_albroker__stopTask(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__stopTask(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__stopTaskResponse
#define SOAP_TYPE_AL_albroker__stopTaskResponse (105)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__stopTaskResponse(struct soap*, struct albroker__stopTaskResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__stopTaskResponse(struct soap*, const struct albroker__stopTaskResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__stopTaskResponse(struct soap*, const struct albroker__stopTaskResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__stopTaskResponse(struct soap*, const char*, int, const struct albroker__stopTaskResponse *, const char*);
SOAP_FMAC3 struct albroker__stopTaskResponse * SOAP_FMAC4 soap_get_albroker__stopTaskResponse(struct soap*, struct albroker__stopTaskResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__stopTaskResponse * SOAP_FMAC4 soap_in_albroker__stopTaskResponse(struct soap*, const char*, struct albroker__stopTaskResponse *, const char*);
SOAP_FMAC5 struct albroker__stopTaskResponse * SOAP_FMAC6 soap_new_albroker__stopTaskResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__stopTaskResponse(struct soap*, struct albroker__stopTaskResponse*);
SOAP_FMAC3 struct albroker__stopTaskResponse * SOAP_FMAC4 soap_instantiate_albroker__stopTaskResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__stopTaskResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getInfo
#define SOAP_TYPE_AL_albroker__getInfo (103)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getInfo(struct soap*, struct albroker__getInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getInfo(struct soap*, const struct albroker__getInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getInfo(struct soap*, const struct albroker__getInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getInfo(struct soap*, const char*, int, const struct albroker__getInfo *, const char*);
SOAP_FMAC3 struct albroker__getInfo * SOAP_FMAC4 soap_get_albroker__getInfo(struct soap*, struct albroker__getInfo *, const char*, const char*);
SOAP_FMAC3 struct albroker__getInfo * SOAP_FMAC4 soap_in_albroker__getInfo(struct soap*, const char*, struct albroker__getInfo *, const char*);
SOAP_FMAC5 struct albroker__getInfo * SOAP_FMAC6 soap_new_albroker__getInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getInfo(struct soap*, struct albroker__getInfo*);
SOAP_FMAC3 struct albroker__getInfo * SOAP_FMAC4 soap_instantiate_albroker__getInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getBrokerName
#define SOAP_TYPE_AL_albroker__getBrokerName (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getBrokerName(struct soap*, struct albroker__getBrokerName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getBrokerName(struct soap*, const struct albroker__getBrokerName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getBrokerName(struct soap*, const struct albroker__getBrokerName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getBrokerName(struct soap*, const char*, int, const struct albroker__getBrokerName *, const char*);
SOAP_FMAC3 struct albroker__getBrokerName * SOAP_FMAC4 soap_get_albroker__getBrokerName(struct soap*, struct albroker__getBrokerName *, const char*, const char*);
SOAP_FMAC3 struct albroker__getBrokerName * SOAP_FMAC4 soap_in_albroker__getBrokerName(struct soap*, const char*, struct albroker__getBrokerName *, const char*);
SOAP_FMAC5 struct albroker__getBrokerName * SOAP_FMAC6 soap_new_albroker__getBrokerName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getBrokerName(struct soap*, struct albroker__getBrokerName*);
SOAP_FMAC3 struct albroker__getBrokerName * SOAP_FMAC4 soap_instantiate_albroker__getBrokerName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getBrokerName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getBrokerNameResponse
#define SOAP_TYPE_AL_albroker__getBrokerNameResponse (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getBrokerNameResponse(struct soap*, struct albroker__getBrokerNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getBrokerNameResponse(struct soap*, const struct albroker__getBrokerNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getBrokerNameResponse(struct soap*, const struct albroker__getBrokerNameResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getBrokerNameResponse(struct soap*, const char*, int, const struct albroker__getBrokerNameResponse *, const char*);
SOAP_FMAC3 struct albroker__getBrokerNameResponse * SOAP_FMAC4 soap_get_albroker__getBrokerNameResponse(struct soap*, struct albroker__getBrokerNameResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getBrokerNameResponse * SOAP_FMAC4 soap_in_albroker__getBrokerNameResponse(struct soap*, const char*, struct albroker__getBrokerNameResponse *, const char*);
SOAP_FMAC5 struct albroker__getBrokerNameResponse * SOAP_FMAC6 soap_new_albroker__getBrokerNameResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getBrokerNameResponse(struct soap*, struct albroker__getBrokerNameResponse*);
SOAP_FMAC3 struct albroker__getBrokerNameResponse * SOAP_FMAC4 soap_instantiate_albroker__getBrokerNameResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getBrokerNameResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__sendBackIP
#define SOAP_TYPE_AL_albroker__sendBackIP (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__sendBackIP(struct soap*, struct albroker__sendBackIP *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__sendBackIP(struct soap*, const struct albroker__sendBackIP *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__sendBackIP(struct soap*, const struct albroker__sendBackIP *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__sendBackIP(struct soap*, const char*, int, const struct albroker__sendBackIP *, const char*);
SOAP_FMAC3 struct albroker__sendBackIP * SOAP_FMAC4 soap_get_albroker__sendBackIP(struct soap*, struct albroker__sendBackIP *, const char*, const char*);
SOAP_FMAC3 struct albroker__sendBackIP * SOAP_FMAC4 soap_in_albroker__sendBackIP(struct soap*, const char*, struct albroker__sendBackIP *, const char*);
SOAP_FMAC5 struct albroker__sendBackIP * SOAP_FMAC6 soap_new_albroker__sendBackIP(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__sendBackIP(struct soap*, struct albroker__sendBackIP*);
SOAP_FMAC3 struct albroker__sendBackIP * SOAP_FMAC4 soap_instantiate_albroker__sendBackIP(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__sendBackIP(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__sendBackIPResponse
#define SOAP_TYPE_AL_albroker__sendBackIPResponse (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__sendBackIPResponse(struct soap*, struct albroker__sendBackIPResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__sendBackIPResponse(struct soap*, const struct albroker__sendBackIPResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__sendBackIPResponse(struct soap*, const struct albroker__sendBackIPResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__sendBackIPResponse(struct soap*, const char*, int, const struct albroker__sendBackIPResponse *, const char*);
SOAP_FMAC3 struct albroker__sendBackIPResponse * SOAP_FMAC4 soap_get_albroker__sendBackIPResponse(struct soap*, struct albroker__sendBackIPResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__sendBackIPResponse * SOAP_FMAC4 soap_in_albroker__sendBackIPResponse(struct soap*, const char*, struct albroker__sendBackIPResponse *, const char*);
SOAP_FMAC5 struct albroker__sendBackIPResponse * SOAP_FMAC6 soap_new_albroker__sendBackIPResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__sendBackIPResponse(struct soap*, struct albroker__sendBackIPResponse*);
SOAP_FMAC3 struct albroker__sendBackIPResponse * SOAP_FMAC4 soap_instantiate_albroker__sendBackIPResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__sendBackIPResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__version
#define SOAP_TYPE_AL_albroker__version (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__version(struct soap*, struct albroker__version *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__version(struct soap*, const struct albroker__version *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__version(struct soap*, const struct albroker__version *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__version(struct soap*, const char*, int, const struct albroker__version *, const char*);
SOAP_FMAC3 struct albroker__version * SOAP_FMAC4 soap_get_albroker__version(struct soap*, struct albroker__version *, const char*, const char*);
SOAP_FMAC3 struct albroker__version * SOAP_FMAC4 soap_in_albroker__version(struct soap*, const char*, struct albroker__version *, const char*);
SOAP_FMAC5 struct albroker__version * SOAP_FMAC6 soap_new_albroker__version(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__version(struct soap*, struct albroker__version*);
SOAP_FMAC3 struct albroker__version * SOAP_FMAC4 soap_instantiate_albroker__version(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__version(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__versionResponse
#define SOAP_TYPE_AL_albroker__versionResponse (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__versionResponse(struct soap*, struct albroker__versionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__versionResponse(struct soap*, const struct albroker__versionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__versionResponse(struct soap*, const struct albroker__versionResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__versionResponse(struct soap*, const char*, int, const struct albroker__versionResponse *, const char*);
SOAP_FMAC3 struct albroker__versionResponse * SOAP_FMAC4 soap_get_albroker__versionResponse(struct soap*, struct albroker__versionResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__versionResponse * SOAP_FMAC4 soap_in_albroker__versionResponse(struct soap*, const char*, struct albroker__versionResponse *, const char*);
SOAP_FMAC5 struct albroker__versionResponse * SOAP_FMAC6 soap_new_albroker__versionResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__versionResponse(struct soap*, struct albroker__versionResponse*);
SOAP_FMAC3 struct albroker__versionResponse * SOAP_FMAC4 soap_instantiate_albroker__versionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__versionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__init
#define SOAP_TYPE_AL_albroker__init (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__init(struct soap*, struct albroker__init *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__init(struct soap*, const struct albroker__init *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__init(struct soap*, const struct albroker__init *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__init(struct soap*, const char*, int, const struct albroker__init *, const char*);
SOAP_FMAC3 struct albroker__init * SOAP_FMAC4 soap_get_albroker__init(struct soap*, struct albroker__init *, const char*, const char*);
SOAP_FMAC3 struct albroker__init * SOAP_FMAC4 soap_in_albroker__init(struct soap*, const char*, struct albroker__init *, const char*);
SOAP_FMAC5 struct albroker__init * SOAP_FMAC6 soap_new_albroker__init(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__init(struct soap*, struct albroker__init*);
SOAP_FMAC3 struct albroker__init * SOAP_FMAC4 soap_instantiate_albroker__init(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__init(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__initResponse
#define SOAP_TYPE_AL_albroker__initResponse (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__initResponse(struct soap*, struct albroker__initResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__initResponse(struct soap*, const struct albroker__initResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__initResponse(struct soap*, const struct albroker__initResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__initResponse(struct soap*, const char*, int, const struct albroker__initResponse *, const char*);
SOAP_FMAC3 struct albroker__initResponse * SOAP_FMAC4 soap_get_albroker__initResponse(struct soap*, struct albroker__initResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__initResponse * SOAP_FMAC4 soap_in_albroker__initResponse(struct soap*, const char*, struct albroker__initResponse *, const char*);
SOAP_FMAC5 struct albroker__initResponse * SOAP_FMAC6 soap_new_albroker__initResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__initResponse(struct soap*, struct albroker__initResponse*);
SOAP_FMAC3 struct albroker__initResponse * SOAP_FMAC4 soap_instantiate_albroker__initResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__initResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getMethodList
#define SOAP_TYPE_AL_albroker__getMethodList (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getMethodList(struct soap*, struct albroker__getMethodList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getMethodList(struct soap*, const struct albroker__getMethodList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getMethodList(struct soap*, const struct albroker__getMethodList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getMethodList(struct soap*, const char*, int, const struct albroker__getMethodList *, const char*);
SOAP_FMAC3 struct albroker__getMethodList * SOAP_FMAC4 soap_get_albroker__getMethodList(struct soap*, struct albroker__getMethodList *, const char*, const char*);
SOAP_FMAC3 struct albroker__getMethodList * SOAP_FMAC4 soap_in_albroker__getMethodList(struct soap*, const char*, struct albroker__getMethodList *, const char*);
SOAP_FMAC5 struct albroker__getMethodList * SOAP_FMAC6 soap_new_albroker__getMethodList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getMethodList(struct soap*, struct albroker__getMethodList*);
SOAP_FMAC3 struct albroker__getMethodList * SOAP_FMAC4 soap_instantiate_albroker__getMethodList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getMethodList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getMethodListResponse
#define SOAP_TYPE_AL_albroker__getMethodListResponse (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getMethodListResponse(struct soap*, struct albroker__getMethodListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getMethodListResponse(struct soap*, const struct albroker__getMethodListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getMethodListResponse(struct soap*, const struct albroker__getMethodListResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getMethodListResponse(struct soap*, const char*, int, const struct albroker__getMethodListResponse *, const char*);
SOAP_FMAC3 struct albroker__getMethodListResponse * SOAP_FMAC4 soap_get_albroker__getMethodListResponse(struct soap*, struct albroker__getMethodListResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getMethodListResponse * SOAP_FMAC4 soap_in_albroker__getMethodListResponse(struct soap*, const char*, struct albroker__getMethodListResponse *, const char*);
SOAP_FMAC5 struct albroker__getMethodListResponse * SOAP_FMAC6 soap_new_albroker__getMethodListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getMethodListResponse(struct soap*, struct albroker__getMethodListResponse*);
SOAP_FMAC3 struct albroker__getMethodListResponse * SOAP_FMAC4 soap_instantiate_albroker__getMethodListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getMethodListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__exit
#define SOAP_TYPE_AL_albroker__exit (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__exit(struct soap*, struct albroker__exit *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__exit(struct soap*, const struct albroker__exit *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__exit(struct soap*, const struct albroker__exit *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__exit(struct soap*, const char*, int, const struct albroker__exit *, const char*);
SOAP_FMAC3 struct albroker__exit * SOAP_FMAC4 soap_get_albroker__exit(struct soap*, struct albroker__exit *, const char*, const char*);
SOAP_FMAC3 struct albroker__exit * SOAP_FMAC4 soap_in_albroker__exit(struct soap*, const char*, struct albroker__exit *, const char*);
SOAP_FMAC5 struct albroker__exit * SOAP_FMAC6 soap_new_albroker__exit(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__exit(struct soap*, struct albroker__exit*);
SOAP_FMAC3 struct albroker__exit * SOAP_FMAC4 soap_instantiate_albroker__exit(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__exit(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getBrokerInfo
#define SOAP_TYPE_AL_albroker__getBrokerInfo (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getBrokerInfo(struct soap*, struct albroker__getBrokerInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getBrokerInfo(struct soap*, const struct albroker__getBrokerInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getBrokerInfo(struct soap*, const struct albroker__getBrokerInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getBrokerInfo(struct soap*, const char*, int, const struct albroker__getBrokerInfo *, const char*);
SOAP_FMAC3 struct albroker__getBrokerInfo * SOAP_FMAC4 soap_get_albroker__getBrokerInfo(struct soap*, struct albroker__getBrokerInfo *, const char*, const char*);
SOAP_FMAC3 struct albroker__getBrokerInfo * SOAP_FMAC4 soap_in_albroker__getBrokerInfo(struct soap*, const char*, struct albroker__getBrokerInfo *, const char*);
SOAP_FMAC5 struct albroker__getBrokerInfo * SOAP_FMAC6 soap_new_albroker__getBrokerInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getBrokerInfo(struct soap*, struct albroker__getBrokerInfo*);
SOAP_FMAC3 struct albroker__getBrokerInfo * SOAP_FMAC4 soap_instantiate_albroker__getBrokerInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getBrokerInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__unregisterModuleReference
#define SOAP_TYPE_AL_albroker__unregisterModuleReference (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__unregisterModuleReference(struct soap*, struct albroker__unregisterModuleReference *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__unregisterModuleReference(struct soap*, const struct albroker__unregisterModuleReference *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__unregisterModuleReference(struct soap*, const struct albroker__unregisterModuleReference *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__unregisterModuleReference(struct soap*, const char*, int, const struct albroker__unregisterModuleReference *, const char*);
SOAP_FMAC3 struct albroker__unregisterModuleReference * SOAP_FMAC4 soap_get_albroker__unregisterModuleReference(struct soap*, struct albroker__unregisterModuleReference *, const char*, const char*);
SOAP_FMAC3 struct albroker__unregisterModuleReference * SOAP_FMAC4 soap_in_albroker__unregisterModuleReference(struct soap*, const char*, struct albroker__unregisterModuleReference *, const char*);
SOAP_FMAC5 struct albroker__unregisterModuleReference * SOAP_FMAC6 soap_new_albroker__unregisterModuleReference(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__unregisterModuleReference(struct soap*, struct albroker__unregisterModuleReference*);
SOAP_FMAC3 struct albroker__unregisterModuleReference * SOAP_FMAC4 soap_instantiate_albroker__unregisterModuleReference(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__unregisterModuleReference(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__unregisterBroker
#define SOAP_TYPE_AL_albroker__unregisterBroker (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__unregisterBroker(struct soap*, struct albroker__unregisterBroker *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__unregisterBroker(struct soap*, const struct albroker__unregisterBroker *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__unregisterBroker(struct soap*, const struct albroker__unregisterBroker *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__unregisterBroker(struct soap*, const char*, int, const struct albroker__unregisterBroker *, const char*);
SOAP_FMAC3 struct albroker__unregisterBroker * SOAP_FMAC4 soap_get_albroker__unregisterBroker(struct soap*, struct albroker__unregisterBroker *, const char*, const char*);
SOAP_FMAC3 struct albroker__unregisterBroker * SOAP_FMAC4 soap_in_albroker__unregisterBroker(struct soap*, const char*, struct albroker__unregisterBroker *, const char*);
SOAP_FMAC5 struct albroker__unregisterBroker * SOAP_FMAC6 soap_new_albroker__unregisterBroker(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__unregisterBroker(struct soap*, struct albroker__unregisterBroker*);
SOAP_FMAC3 struct albroker__unregisterBroker * SOAP_FMAC4 soap_instantiate_albroker__unregisterBroker(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__unregisterBroker(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__unregisterBrokerResponse
#define SOAP_TYPE_AL_albroker__unregisterBrokerResponse (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__unregisterBrokerResponse(struct soap*, struct albroker__unregisterBrokerResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__unregisterBrokerResponse(struct soap*, const struct albroker__unregisterBrokerResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__unregisterBrokerResponse(struct soap*, const struct albroker__unregisterBrokerResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__unregisterBrokerResponse(struct soap*, const char*, int, const struct albroker__unregisterBrokerResponse *, const char*);
SOAP_FMAC3 struct albroker__unregisterBrokerResponse * SOAP_FMAC4 soap_get_albroker__unregisterBrokerResponse(struct soap*, struct albroker__unregisterBrokerResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__unregisterBrokerResponse * SOAP_FMAC4 soap_in_albroker__unregisterBrokerResponse(struct soap*, const char*, struct albroker__unregisterBrokerResponse *, const char*);
SOAP_FMAC5 struct albroker__unregisterBrokerResponse * SOAP_FMAC6 soap_new_albroker__unregisterBrokerResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__unregisterBrokerResponse(struct soap*, struct albroker__unregisterBrokerResponse*);
SOAP_FMAC3 struct albroker__unregisterBrokerResponse * SOAP_FMAC4 soap_instantiate_albroker__unregisterBrokerResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__unregisterBrokerResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__registerBroker
#define SOAP_TYPE_AL_albroker__registerBroker (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__registerBroker(struct soap*, struct albroker__registerBroker *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__registerBroker(struct soap*, const struct albroker__registerBroker *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__registerBroker(struct soap*, const struct albroker__registerBroker *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__registerBroker(struct soap*, const char*, int, const struct albroker__registerBroker *, const char*);
SOAP_FMAC3 struct albroker__registerBroker * SOAP_FMAC4 soap_get_albroker__registerBroker(struct soap*, struct albroker__registerBroker *, const char*, const char*);
SOAP_FMAC3 struct albroker__registerBroker * SOAP_FMAC4 soap_in_albroker__registerBroker(struct soap*, const char*, struct albroker__registerBroker *, const char*);
SOAP_FMAC5 struct albroker__registerBroker * SOAP_FMAC6 soap_new_albroker__registerBroker(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__registerBroker(struct soap*, struct albroker__registerBroker*);
SOAP_FMAC3 struct albroker__registerBroker * SOAP_FMAC4 soap_instantiate_albroker__registerBroker(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__registerBroker(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__registerBrokerResponse
#define SOAP_TYPE_AL_albroker__registerBrokerResponse (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__registerBrokerResponse(struct soap*, struct albroker__registerBrokerResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__registerBrokerResponse(struct soap*, const struct albroker__registerBrokerResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__registerBrokerResponse(struct soap*, const struct albroker__registerBrokerResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__registerBrokerResponse(struct soap*, const char*, int, const struct albroker__registerBrokerResponse *, const char*);
SOAP_FMAC3 struct albroker__registerBrokerResponse * SOAP_FMAC4 soap_get_albroker__registerBrokerResponse(struct soap*, struct albroker__registerBrokerResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__registerBrokerResponse * SOAP_FMAC4 soap_in_albroker__registerBrokerResponse(struct soap*, const char*, struct albroker__registerBrokerResponse *, const char*);
SOAP_FMAC5 struct albroker__registerBrokerResponse * SOAP_FMAC6 soap_new_albroker__registerBrokerResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__registerBrokerResponse(struct soap*, struct albroker__registerBrokerResponse*);
SOAP_FMAC3 struct albroker__registerBrokerResponse * SOAP_FMAC4 soap_instantiate_albroker__registerBrokerResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__registerBrokerResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getBrokerList
#define SOAP_TYPE_AL_albroker__getBrokerList (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getBrokerList(struct soap*, struct albroker__getBrokerList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getBrokerList(struct soap*, const struct albroker__getBrokerList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getBrokerList(struct soap*, const struct albroker__getBrokerList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getBrokerList(struct soap*, const char*, int, const struct albroker__getBrokerList *, const char*);
SOAP_FMAC3 struct albroker__getBrokerList * SOAP_FMAC4 soap_get_albroker__getBrokerList(struct soap*, struct albroker__getBrokerList *, const char*, const char*);
SOAP_FMAC3 struct albroker__getBrokerList * SOAP_FMAC4 soap_in_albroker__getBrokerList(struct soap*, const char*, struct albroker__getBrokerList *, const char*);
SOAP_FMAC5 struct albroker__getBrokerList * SOAP_FMAC6 soap_new_albroker__getBrokerList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getBrokerList(struct soap*, struct albroker__getBrokerList*);
SOAP_FMAC3 struct albroker__getBrokerList * SOAP_FMAC4 soap_instantiate_albroker__getBrokerList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getBrokerList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getGlobalModuleList
#define SOAP_TYPE_AL_albroker__getGlobalModuleList (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getGlobalModuleList(struct soap*, struct albroker__getGlobalModuleList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getGlobalModuleList(struct soap*, const struct albroker__getGlobalModuleList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getGlobalModuleList(struct soap*, const struct albroker__getGlobalModuleList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getGlobalModuleList(struct soap*, const char*, int, const struct albroker__getGlobalModuleList *, const char*);
SOAP_FMAC3 struct albroker__getGlobalModuleList * SOAP_FMAC4 soap_get_albroker__getGlobalModuleList(struct soap*, struct albroker__getGlobalModuleList *, const char*, const char*);
SOAP_FMAC3 struct albroker__getGlobalModuleList * SOAP_FMAC4 soap_in_albroker__getGlobalModuleList(struct soap*, const char*, struct albroker__getGlobalModuleList *, const char*);
SOAP_FMAC5 struct albroker__getGlobalModuleList * SOAP_FMAC6 soap_new_albroker__getGlobalModuleList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getGlobalModuleList(struct soap*, struct albroker__getGlobalModuleList*);
SOAP_FMAC3 struct albroker__getGlobalModuleList * SOAP_FMAC4 soap_instantiate_albroker__getGlobalModuleList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getGlobalModuleList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getModuleList
#define SOAP_TYPE_AL_albroker__getModuleList (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getModuleList(struct soap*, struct albroker__getModuleList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getModuleList(struct soap*, const struct albroker__getModuleList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getModuleList(struct soap*, const struct albroker__getModuleList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getModuleList(struct soap*, const char*, int, const struct albroker__getModuleList *, const char*);
SOAP_FMAC3 struct albroker__getModuleList * SOAP_FMAC4 soap_get_albroker__getModuleList(struct soap*, struct albroker__getModuleList *, const char*, const char*);
SOAP_FMAC3 struct albroker__getModuleList * SOAP_FMAC4 soap_in_albroker__getModuleList(struct soap*, const char*, struct albroker__getModuleList *, const char*);
SOAP_FMAC5 struct albroker__getModuleList * SOAP_FMAC6 soap_new_albroker__getModuleList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getModuleList(struct soap*, struct albroker__getModuleList*);
SOAP_FMAC3 struct albroker__getModuleList * SOAP_FMAC4 soap_instantiate_albroker__getModuleList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getModuleList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__exploreToGetModuleByName
#define SOAP_TYPE_AL_albroker__exploreToGetModuleByName (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__exploreToGetModuleByName(struct soap*, struct albroker__exploreToGetModuleByName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__exploreToGetModuleByName(struct soap*, const struct albroker__exploreToGetModuleByName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__exploreToGetModuleByName(struct soap*, const struct albroker__exploreToGetModuleByName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__exploreToGetModuleByName(struct soap*, const char*, int, const struct albroker__exploreToGetModuleByName *, const char*);
SOAP_FMAC3 struct albroker__exploreToGetModuleByName * SOAP_FMAC4 soap_get_albroker__exploreToGetModuleByName(struct soap*, struct albroker__exploreToGetModuleByName *, const char*, const char*);
SOAP_FMAC3 struct albroker__exploreToGetModuleByName * SOAP_FMAC4 soap_in_albroker__exploreToGetModuleByName(struct soap*, const char*, struct albroker__exploreToGetModuleByName *, const char*);
SOAP_FMAC5 struct albroker__exploreToGetModuleByName * SOAP_FMAC6 soap_new_albroker__exploreToGetModuleByName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__exploreToGetModuleByName(struct soap*, struct albroker__exploreToGetModuleByName*);
SOAP_FMAC3 struct albroker__exploreToGetModuleByName * SOAP_FMAC4 soap_instantiate_albroker__exploreToGetModuleByName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__exploreToGetModuleByName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getModuleByName
#define SOAP_TYPE_AL_albroker__getModuleByName (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getModuleByName(struct soap*, struct albroker__getModuleByName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getModuleByName(struct soap*, const struct albroker__getModuleByName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getModuleByName(struct soap*, const struct albroker__getModuleByName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getModuleByName(struct soap*, const char*, int, const struct albroker__getModuleByName *, const char*);
SOAP_FMAC3 struct albroker__getModuleByName * SOAP_FMAC4 soap_get_albroker__getModuleByName(struct soap*, struct albroker__getModuleByName *, const char*, const char*);
SOAP_FMAC3 struct albroker__getModuleByName * SOAP_FMAC4 soap_in_albroker__getModuleByName(struct soap*, const char*, struct albroker__getModuleByName *, const char*);
SOAP_FMAC5 struct albroker__getModuleByName * SOAP_FMAC6 soap_new_albroker__getModuleByName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getModuleByName(struct soap*, struct albroker__getModuleByName*);
SOAP_FMAC3 struct albroker__getModuleByName * SOAP_FMAC4 soap_instantiate_albroker__getModuleByName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getModuleByName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__pCallNaoqi
#define SOAP_TYPE_AL_albroker__pCallNaoqi (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__pCallNaoqi(struct soap*, struct albroker__pCallNaoqi *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__pCallNaoqi(struct soap*, const struct albroker__pCallNaoqi *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__pCallNaoqi(struct soap*, const struct albroker__pCallNaoqi *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__pCallNaoqi(struct soap*, const char*, int, const struct albroker__pCallNaoqi *, const char*);
SOAP_FMAC3 struct albroker__pCallNaoqi * SOAP_FMAC4 soap_get_albroker__pCallNaoqi(struct soap*, struct albroker__pCallNaoqi *, const char*, const char*);
SOAP_FMAC3 struct albroker__pCallNaoqi * SOAP_FMAC4 soap_in_albroker__pCallNaoqi(struct soap*, const char*, struct albroker__pCallNaoqi *, const char*);
SOAP_FMAC5 struct albroker__pCallNaoqi * SOAP_FMAC6 soap_new_albroker__pCallNaoqi(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__pCallNaoqi(struct soap*, struct albroker__pCallNaoqi*);
SOAP_FMAC3 struct albroker__pCallNaoqi * SOAP_FMAC4 soap_instantiate_albroker__pCallNaoqi(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__pCallNaoqi(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__pCallNaoqiN
#define SOAP_TYPE_AL_albroker__pCallNaoqiN (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__pCallNaoqiN(struct soap*, struct albroker__pCallNaoqiN *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__pCallNaoqiN(struct soap*, const struct albroker__pCallNaoqiN *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__pCallNaoqiN(struct soap*, const struct albroker__pCallNaoqiN *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__pCallNaoqiN(struct soap*, const char*, int, const struct albroker__pCallNaoqiN *, const char*);
SOAP_FMAC3 struct albroker__pCallNaoqiN * SOAP_FMAC4 soap_get_albroker__pCallNaoqiN(struct soap*, struct albroker__pCallNaoqiN *, const char*, const char*);
SOAP_FMAC3 struct albroker__pCallNaoqiN * SOAP_FMAC4 soap_in_albroker__pCallNaoqiN(struct soap*, const char*, struct albroker__pCallNaoqiN *, const char*);
SOAP_FMAC5 struct albroker__pCallNaoqiN * SOAP_FMAC6 soap_new_albroker__pCallNaoqiN(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__pCallNaoqiN(struct soap*, struct albroker__pCallNaoqiN*);
SOAP_FMAC3 struct albroker__pCallNaoqiN * SOAP_FMAC4 soap_instantiate_albroker__pCallNaoqiN(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__pCallNaoqiN(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__callNaoqi2
#define SOAP_TYPE_AL_albroker__callNaoqi2 (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__callNaoqi2(struct soap*, struct albroker__callNaoqi2 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__callNaoqi2(struct soap*, const struct albroker__callNaoqi2 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__callNaoqi2(struct soap*, const struct albroker__callNaoqi2 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__callNaoqi2(struct soap*, const char*, int, const struct albroker__callNaoqi2 *, const char*);
SOAP_FMAC3 struct albroker__callNaoqi2 * SOAP_FMAC4 soap_get_albroker__callNaoqi2(struct soap*, struct albroker__callNaoqi2 *, const char*, const char*);
SOAP_FMAC3 struct albroker__callNaoqi2 * SOAP_FMAC4 soap_in_albroker__callNaoqi2(struct soap*, const char*, struct albroker__callNaoqi2 *, const char*);
SOAP_FMAC5 struct albroker__callNaoqi2 * SOAP_FMAC6 soap_new_albroker__callNaoqi2(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__callNaoqi2(struct soap*, struct albroker__callNaoqi2*);
SOAP_FMAC3 struct albroker__callNaoqi2 * SOAP_FMAC4 soap_instantiate_albroker__callNaoqi2(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__callNaoqi2(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__callNaoqi
#define SOAP_TYPE_AL_albroker__callNaoqi (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__callNaoqi(struct soap*, struct albroker__callNaoqi *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__callNaoqi(struct soap*, const struct albroker__callNaoqi *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__callNaoqi(struct soap*, const struct albroker__callNaoqi *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__callNaoqi(struct soap*, const char*, int, const struct albroker__callNaoqi *, const char*);
SOAP_FMAC3 struct albroker__callNaoqi * SOAP_FMAC4 soap_get_albroker__callNaoqi(struct soap*, struct albroker__callNaoqi *, const char*, const char*);
SOAP_FMAC3 struct albroker__callNaoqi * SOAP_FMAC4 soap_in_albroker__callNaoqi(struct soap*, const char*, struct albroker__callNaoqi *, const char*);
SOAP_FMAC5 struct albroker__callNaoqi * SOAP_FMAC6 soap_new_albroker__callNaoqi(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__callNaoqi(struct soap*, struct albroker__callNaoqi*);
SOAP_FMAC3 struct albroker__callNaoqi * SOAP_FMAC4 soap_instantiate_albroker__callNaoqi(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__callNaoqi(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getDebugTaskListResponse
#define SOAP_TYPE_AL_albroker__getDebugTaskListResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getDebugTaskListResponse(struct soap*, struct albroker__getDebugTaskListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getDebugTaskListResponse(struct soap*, const struct albroker__getDebugTaskListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getDebugTaskListResponse(struct soap*, const struct albroker__getDebugTaskListResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getDebugTaskListResponse(struct soap*, const char*, int, const struct albroker__getDebugTaskListResponse *, const char*);
SOAP_FMAC3 struct albroker__getDebugTaskListResponse * SOAP_FMAC4 soap_get_albroker__getDebugTaskListResponse(struct soap*, struct albroker__getDebugTaskListResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getDebugTaskListResponse * SOAP_FMAC4 soap_in_albroker__getDebugTaskListResponse(struct soap*, const char*, struct albroker__getDebugTaskListResponse *, const char*);
SOAP_FMAC5 struct albroker__getDebugTaskListResponse * SOAP_FMAC6 soap_new_albroker__getDebugTaskListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getDebugTaskListResponse(struct soap*, struct albroker__getDebugTaskListResponse*);
SOAP_FMAC3 struct albroker__getDebugTaskListResponse * SOAP_FMAC4 soap_instantiate_albroker__getDebugTaskListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getDebugTaskListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getGlobalModuleListResponse
#define SOAP_TYPE_AL_albroker__getGlobalModuleListResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getGlobalModuleListResponse(struct soap*, struct albroker__getGlobalModuleListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getGlobalModuleListResponse(struct soap*, const struct albroker__getGlobalModuleListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getGlobalModuleListResponse(struct soap*, const struct albroker__getGlobalModuleListResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getGlobalModuleListResponse(struct soap*, const char*, int, const struct albroker__getGlobalModuleListResponse *, const char*);
SOAP_FMAC3 struct albroker__getGlobalModuleListResponse * SOAP_FMAC4 soap_get_albroker__getGlobalModuleListResponse(struct soap*, struct albroker__getGlobalModuleListResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getGlobalModuleListResponse * SOAP_FMAC4 soap_in_albroker__getGlobalModuleListResponse(struct soap*, const char*, struct albroker__getGlobalModuleListResponse *, const char*);
SOAP_FMAC5 struct albroker__getGlobalModuleListResponse * SOAP_FMAC6 soap_new_albroker__getGlobalModuleListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getGlobalModuleListResponse(struct soap*, struct albroker__getGlobalModuleListResponse*);
SOAP_FMAC3 struct albroker__getGlobalModuleListResponse * SOAP_FMAC4 soap_instantiate_albroker__getGlobalModuleListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getGlobalModuleListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getBrokerListResponse
#define SOAP_TYPE_AL_albroker__getBrokerListResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getBrokerListResponse(struct soap*, struct albroker__getBrokerListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getBrokerListResponse(struct soap*, const struct albroker__getBrokerListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getBrokerListResponse(struct soap*, const struct albroker__getBrokerListResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getBrokerListResponse(struct soap*, const char*, int, const struct albroker__getBrokerListResponse *, const char*);
SOAP_FMAC3 struct albroker__getBrokerListResponse * SOAP_FMAC4 soap_get_albroker__getBrokerListResponse(struct soap*, struct albroker__getBrokerListResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getBrokerListResponse * SOAP_FMAC4 soap_in_albroker__getBrokerListResponse(struct soap*, const char*, struct albroker__getBrokerListResponse *, const char*);
SOAP_FMAC5 struct albroker__getBrokerListResponse * SOAP_FMAC6 soap_new_albroker__getBrokerListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getBrokerListResponse(struct soap*, struct albroker__getBrokerListResponse*);
SOAP_FMAC3 struct albroker__getBrokerListResponse * SOAP_FMAC4 soap_instantiate_albroker__getBrokerListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getBrokerListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getModuleListResponse
#define SOAP_TYPE_AL_albroker__getModuleListResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getModuleListResponse(struct soap*, struct albroker__getModuleListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getModuleListResponse(struct soap*, const struct albroker__getModuleListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getModuleListResponse(struct soap*, const struct albroker__getModuleListResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getModuleListResponse(struct soap*, const char*, int, const struct albroker__getModuleListResponse *, const char*);
SOAP_FMAC3 struct albroker__getModuleListResponse * SOAP_FMAC4 soap_get_albroker__getModuleListResponse(struct soap*, struct albroker__getModuleListResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getModuleListResponse * SOAP_FMAC4 soap_in_albroker__getModuleListResponse(struct soap*, const char*, struct albroker__getModuleListResponse *, const char*);
SOAP_FMAC5 struct albroker__getModuleListResponse * SOAP_FMAC6 soap_new_albroker__getModuleListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getModuleListResponse(struct soap*, struct albroker__getModuleListResponse*);
SOAP_FMAC3 struct albroker__getModuleListResponse * SOAP_FMAC4 soap_instantiate_albroker__getModuleListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getModuleListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__pCallNaoqiNResponse
#define SOAP_TYPE_AL_albroker__pCallNaoqiNResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__pCallNaoqiNResponse(struct soap*, struct albroker__pCallNaoqiNResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__pCallNaoqiNResponse(struct soap*, const struct albroker__pCallNaoqiNResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__pCallNaoqiNResponse(struct soap*, const struct albroker__pCallNaoqiNResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__pCallNaoqiNResponse(struct soap*, const char*, int, const struct albroker__pCallNaoqiNResponse *, const char*);
SOAP_FMAC3 struct albroker__pCallNaoqiNResponse * SOAP_FMAC4 soap_get_albroker__pCallNaoqiNResponse(struct soap*, struct albroker__pCallNaoqiNResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__pCallNaoqiNResponse * SOAP_FMAC4 soap_in_albroker__pCallNaoqiNResponse(struct soap*, const char*, struct albroker__pCallNaoqiNResponse *, const char*);
SOAP_FMAC5 struct albroker__pCallNaoqiNResponse * SOAP_FMAC6 soap_new_albroker__pCallNaoqiNResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__pCallNaoqiNResponse(struct soap*, struct albroker__pCallNaoqiNResponse*);
SOAP_FMAC3 struct albroker__pCallNaoqiNResponse * SOAP_FMAC4 soap_instantiate_albroker__pCallNaoqiNResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__pCallNaoqiNResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__callNaoqi2Response
#define SOAP_TYPE_AL_albroker__callNaoqi2Response (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__callNaoqi2Response(struct soap*, struct albroker__callNaoqi2Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__callNaoqi2Response(struct soap*, const struct albroker__callNaoqi2Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__callNaoqi2Response(struct soap*, const struct albroker__callNaoqi2Response *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__callNaoqi2Response(struct soap*, const char*, int, const struct albroker__callNaoqi2Response *, const char*);
SOAP_FMAC3 struct albroker__callNaoqi2Response * SOAP_FMAC4 soap_get_albroker__callNaoqi2Response(struct soap*, struct albroker__callNaoqi2Response *, const char*, const char*);
SOAP_FMAC3 struct albroker__callNaoqi2Response * SOAP_FMAC4 soap_in_albroker__callNaoqi2Response(struct soap*, const char*, struct albroker__callNaoqi2Response *, const char*);
SOAP_FMAC5 struct albroker__callNaoqi2Response * SOAP_FMAC6 soap_new_albroker__callNaoqi2Response(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__callNaoqi2Response(struct soap*, struct albroker__callNaoqi2Response*);
SOAP_FMAC3 struct albroker__callNaoqi2Response * SOAP_FMAC4 soap_instantiate_albroker__callNaoqi2Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__callNaoqi2Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__callNaoqiResponse
#define SOAP_TYPE_AL_albroker__callNaoqiResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__callNaoqiResponse(struct soap*, struct albroker__callNaoqiResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__callNaoqiResponse(struct soap*, const struct albroker__callNaoqiResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__callNaoqiResponse(struct soap*, const struct albroker__callNaoqiResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__callNaoqiResponse(struct soap*, const char*, int, const struct albroker__callNaoqiResponse *, const char*);
SOAP_FMAC3 struct albroker__callNaoqiResponse * SOAP_FMAC4 soap_get_albroker__callNaoqiResponse(struct soap*, struct albroker__callNaoqiResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__callNaoqiResponse * SOAP_FMAC4 soap_in_albroker__callNaoqiResponse(struct soap*, const char*, struct albroker__callNaoqiResponse *, const char*);
SOAP_FMAC5 struct albroker__callNaoqiResponse * SOAP_FMAC6 soap_new_albroker__callNaoqiResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__callNaoqiResponse(struct soap*, struct albroker__callNaoqiResponse*);
SOAP_FMAC3 struct albroker__callNaoqiResponse * SOAP_FMAC4 soap_instantiate_albroker__callNaoqiResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__callNaoqiResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getModuleByNameResponse
#define SOAP_TYPE_AL_albroker__getModuleByNameResponse (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getModuleByNameResponse(struct soap*, struct albroker__getModuleByNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getModuleByNameResponse(struct soap*, const struct albroker__getModuleByNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getModuleByNameResponse(struct soap*, const struct albroker__getModuleByNameResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getModuleByNameResponse(struct soap*, const char*, int, const struct albroker__getModuleByNameResponse *, const char*);
SOAP_FMAC3 struct albroker__getModuleByNameResponse * SOAP_FMAC4 soap_get_albroker__getModuleByNameResponse(struct soap*, struct albroker__getModuleByNameResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getModuleByNameResponse * SOAP_FMAC4 soap_in_albroker__getModuleByNameResponse(struct soap*, const char*, struct albroker__getModuleByNameResponse *, const char*);
SOAP_FMAC5 struct albroker__getModuleByNameResponse * SOAP_FMAC6 soap_new_albroker__getModuleByNameResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getModuleByNameResponse(struct soap*, struct albroker__getModuleByNameResponse*);
SOAP_FMAC3 struct albroker__getModuleByNameResponse * SOAP_FMAC4 soap_instantiate_albroker__getModuleByNameResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getModuleByNameResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__exploreToGetModuleByNameResponse
#define SOAP_TYPE_AL_albroker__exploreToGetModuleByNameResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__exploreToGetModuleByNameResponse(struct soap*, struct albroker__exploreToGetModuleByNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__exploreToGetModuleByNameResponse(struct soap*, const struct albroker__exploreToGetModuleByNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__exploreToGetModuleByNameResponse(struct soap*, const struct albroker__exploreToGetModuleByNameResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__exploreToGetModuleByNameResponse(struct soap*, const char*, int, const struct albroker__exploreToGetModuleByNameResponse *, const char*);
SOAP_FMAC3 struct albroker__exploreToGetModuleByNameResponse * SOAP_FMAC4 soap_get_albroker__exploreToGetModuleByNameResponse(struct soap*, struct albroker__exploreToGetModuleByNameResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__exploreToGetModuleByNameResponse * SOAP_FMAC4 soap_in_albroker__exploreToGetModuleByNameResponse(struct soap*, const char*, struct albroker__exploreToGetModuleByNameResponse *, const char*);
SOAP_FMAC5 struct albroker__exploreToGetModuleByNameResponse * SOAP_FMAC6 soap_new_albroker__exploreToGetModuleByNameResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__exploreToGetModuleByNameResponse(struct soap*, struct albroker__exploreToGetModuleByNameResponse*);
SOAP_FMAC3 struct albroker__exploreToGetModuleByNameResponse * SOAP_FMAC4 soap_instantiate_albroker__exploreToGetModuleByNameResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__exploreToGetModuleByNameResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_albroker__getBrokerInfoResponse
#define SOAP_TYPE_AL_albroker__getBrokerInfoResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_albroker__getBrokerInfoResponse(struct soap*, struct albroker__getBrokerInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_albroker__getBrokerInfoResponse(struct soap*, const struct albroker__getBrokerInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_albroker__getBrokerInfoResponse(struct soap*, const struct albroker__getBrokerInfoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_albroker__getBrokerInfoResponse(struct soap*, const char*, int, const struct albroker__getBrokerInfoResponse *, const char*);
SOAP_FMAC3 struct albroker__getBrokerInfoResponse * SOAP_FMAC4 soap_get_albroker__getBrokerInfoResponse(struct soap*, struct albroker__getBrokerInfoResponse *, const char*, const char*);
SOAP_FMAC3 struct albroker__getBrokerInfoResponse * SOAP_FMAC4 soap_in_albroker__getBrokerInfoResponse(struct soap*, const char*, struct albroker__getBrokerInfoResponse *, const char*);
SOAP_FMAC5 struct albroker__getBrokerInfoResponse * SOAP_FMAC6 soap_new_albroker__getBrokerInfoResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_albroker__getBrokerInfoResponse(struct soap*, struct albroker__getBrokerInfoResponse*);
SOAP_FMAC3 struct albroker__getBrokerInfoResponse * SOAP_FMAC4 soap_instantiate_albroker__getBrokerInfoResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_albroker__getBrokerInfoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_AL_PointerToSOAP_ENV__Reason (120)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_AL_PointerToSOAP_ENV__Detail (119)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_AL_PointerToSOAP_ENV__Code
#define SOAP_TYPE_AL_PointerToSOAP_ENV__Code (115)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_AL_PointerToxsd__int
#define SOAP_TYPE_AL_PointerToxsd__int (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__int(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__int(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__int(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToxsd__int(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToxsd__int(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE_AL__QName
#define SOAP_TYPE_AL__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_AL_string
#define SOAP_TYPE_AL_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_AL_std__vectorTemplateOfxsd__string
#define SOAP_TYPE_AL_std__vectorTemplateOfxsd__string (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfxsd__string(struct soap*, std::vector<std::string >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfxsd__string(struct soap*, const std::vector<std::string >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfxsd__string(struct soap*, const char*, int, const std::vector<std::string >*, const char*);
SOAP_FMAC3 std::vector<std::string >* SOAP_FMAC4 soap_in_std__vectorTemplateOfxsd__string(struct soap*, const char*, std::vector<std::string >*, const char*);
SOAP_FMAC5 std::vector<std::string > * SOAP_FMAC6 soap_new_std__vectorTemplateOfxsd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfxsd__string(struct soap*, std::vector<std::string >*);
SOAP_FMAC3 std::vector<std::string > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfxsd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfxsd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_AL_std__vectorTemplateOfal__ALModuleInfo
#define SOAP_TYPE_AL_std__vectorTemplateOfal__ALModuleInfo (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfal__ALModuleInfo(struct soap*, std::vector<al__ALModuleInfo >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfal__ALModuleInfo(struct soap*, const std::vector<al__ALModuleInfo >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfal__ALModuleInfo(struct soap*, const char*, int, const std::vector<al__ALModuleInfo >*, const char*);
SOAP_FMAC3 std::vector<al__ALModuleInfo >* SOAP_FMAC4 soap_in_std__vectorTemplateOfal__ALModuleInfo(struct soap*, const char*, std::vector<al__ALModuleInfo >*, const char*);
SOAP_FMAC5 std::vector<al__ALModuleInfo > * SOAP_FMAC6 soap_new_std__vectorTemplateOfal__ALModuleInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_std__vectorTemplateOfal__ALModuleInfo(struct soap*, std::vector<al__ALModuleInfo >*);
SOAP_FMAC3 std::vector<al__ALModuleInfo > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfal__ALModuleInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfal__ALModuleInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

} // namespace AL


#endif

/* End of ALH.h */
